language: bash
sudo: true
services:
  - docker

before_install:
  - docker info
  - docker version
  
  - echo "==> Build with Docker ..."
  
  # Debian
  - docker build -f tests/Dockerfile.debian8 -t kalug1605-ansible-demo:debian8 .    | tee build_result.debian8

  # Ubuntu
  #- docker build -f tests/Dockerfile.ubuntu1404  -t kalug1605-ansible-demo:ubuntu1404 . | tee build_result.ubuntu14
  
  # CentOS
  #- docker build -f tests/Dockerfile.centos7 -t kalug1605-ansible-demo:centos7 .    | tee build_result.centos7
  
script:
  - echo "==> Run Test case ..."
  
  - grep '00:00:00 nginx' build_result.debian8
  #- grep '00:00:00 nginx' build_result.centos7
  #- grep '00:00:00 nginx' build_result.ubuntu1404

