# Dockerfile for building image that contains software stack provisioned by Ansible.
#
# USAGE:
#   $ docker build -t kalug1605-ansible-demo .
#
# Version  1.1
#


# pull base image
FROM williamyeh/ansible:debian8-onbuild

MAINTAINER Chu-Siang Lai <chusiang.lai@gmail.com>

#
# build phase
#

# fix policy-rc.d for Docker
# @see http://www.monblocnotes.com/node/2057
# @see http://askubuntu.com/a/365912
RUN sed -i -e 's/exit\s\s*101/exit 0/' /usr/sbin/policy-rc.d

# ==> Specify requirements filename;  default = "requirements.yml"
#ENV REQUIREMENTS  requirements.yml

#RUN echo "===> Installing curl for testing purpose..."  && \
#    DEBIAN_FRONTEND=noninteractive  \
#    apt-get install -y -f curl

ENV PLAYBOOK setup.yml
RUN ansible-playbook-wrapper -vvv

EXPOSE 80

#
# test phase
#

#RUN echo "===> Installing curl for testing purpose..."  && \
#    DEBIAN_FRONTEND=noninteractive  \
#    apt-get install -y -f curl

CMD service nginx start && \
  tail -f /dev/null

